### ISSUE TITLE
Counter not shown

### ISSUE THREAD

**Issue by HighCommander4** [DaAwesomeP/tab-counter#10]
I installed the extension, but I don't see the counter anywhere. Am I looking for it in the wrong place? I would expect it to be in the toolbar to the right of the search bar. I also checked in Customize view, it's not there either.

Running Firefox 59 Nightly.

**Comment by Smile4ever** [comment]
Which opearting system are you using?

**Comment by HighCommander4** [comment]
Debian Linux.

**Comment by DaAwesomeP** [comment]
@HighCommander4 I apologize for the late reply. It should appear in the tab bar by default on newer versions of Firefox. Are you using Firefox ESR included in Debian stable or standard Firefox?

**Comment by DaAwesomeP** [comment]
@HighCommander4 The addon works flawlessly for me on FF Nightly 59.0a1 2017-12-10 x64 on Debian 9 stable. The addon will have a black badge by default.

**Comment by HighCommander4** [comment]
I am using Firefox Nightly on Debian 9 as well, but I'm using Tree Style Tab, and I've used userChrome.css to hide the real tab bar (since it duplicates the information in Tree Style Tab's sidebar). I guess that's why I'm not seeing the badge.

Is there a way to make the badge show in the area to the right of the search bar instead? (Or, even better, as part of Tree Style Tab's sidebar, but I don't know if that's possible.)

**Comment by DaAwesomeP** [comment]
Firefox controls the actual placement beyond whether or not to prefer the tab bar or main toolbar. I would recommend temporarily disabling Tree Style Tab and commenting out your changes in userChrome.css, moving the badge where you want it, and then re-enabling your modifications.

I'm going to close this since it doesn't appear to be an issue with the addon. Please comment if you encounter further issues.

**Comment by HighCommander4** [comment]
Thanks, it's working fine after doing what you suggested!

My only other feedback is that the number is kind of hard to read because it's small. I notice it only takes up the top-right quarter of the icon - would it be possible to make it take up the entire icon instead?

**Comment by DaAwesomeP** [comment]
Unfortunately, Firefox controls the text size of the badge, and I cannot adjust that in the addon. You can probably adjust it in userChrome.css though. Here is something related from a quick Google search (I don't know if this CSS works): https://support.mozilla.org/en-US/questions/1181966

I wish Mozilla would allow for addons to modify userChrome.css. I could redraw an icon with the number in it (see #8), but I am worried about performance there.
