### ISSUE TITLE
Add option to change badge text color

### ISSUE THREAD

**Issue by keeganwitt** [DaAwesomeP/tab-counter#13]
For example, if I want the background to be white, text disappears because I can't set the text color and it's white by default.

**Comment by DaAwesomeP** [comment]
Unfortunately, this is a limitation of Firefox. The WebExtensions API only allows for the badge background color to be controlled.

**Comment by keeganwitt** [comment]
Bummer.  Thanks for the reply (and for creating this extension) :)

**Comment by keeganwitt** [comment]
Oh, there's an issue for adding this feature by the way: https://bugzilla.mozilla.org/show_bug.cgi?format=default&id=1424620

**Comment by keeganwitt** [comment]
Firefox 63 adds the ability to set this.

**Comment by DaAwesomeP** [comment]
@keeganwitt Awesome! I'll add the feature as soon as I get a chance!

**Comment by Loirooriol** [comment]
You can use https://github.com/Loirooriol/tab-counter-plus meanwhile, I implemented the feature 2 months ago :P

**Comment by DaAwesomeP** [comment]
Hi all,
I have released v0.4.0 on GitHub and AMO! You will find new options to set the the text badge color if you are in Firefox v63 or above.

https://github.com/DaAwesomeP/tab-counter/releases/tag/v0.4.0
https://addons.mozilla.org/en-US/firefox/addon/tab-counter-webext/versions/?page=1#version-0.4.0
