### ISSUE TITLE
"Both" shows number of windows, not the total in all windows

### ISSUE THREAD

**Issue by 1j01** [DaAwesomeP/tab-counter#15]

**Comment by adigitoleo** [comment]
Can confirm this issue for Opera 52.0 as of May 2018.

**Comment by DaAwesomeP** [comment]
@1j01 which browser and version are you in?
I am planning an update. I will test this bug. Thank you for reporting it.

**Comment by DaAwesomeP** [comment]
I'm having a hard time replicating this bug. @1j01 @adigitoleo Would you mind providing a screenshot of miscounted badge, your settings page, and what the popup looks like when clicking the icon? Thanks!

**Comment by DaAwesomeP** [comment]
> Okay, looking at the code, it obviously wouldn't give the number of windows, except by coincidence.
It was the 4 character limit.

@1j01 Ah! I am probably going to remove that feature; it is the cause of a lot of trouble.

> Is it possible to set a dynamic SVG as the icon instead? It would be really easy to lay it out then where it can show both numbers fully, just with one number above the other (or maybe get a bit fancy with a solidus).

I would accept pull requests for that ability. Unfortunately, I don't have time to develop it at the moment. I would also be concerned with how much more memory would be required for Firefox to store an unique SVG for every single tab.

**Comment by DaAwesomeP** [comment]
@1j01 That looks very nice!

I'm still concerned about the amount of memory required to have a unique `ImageData` object for each tab. @dev-rke do you have any insight into this? I also wonder how this will work with retina and higher resolution displays at higher lower DPIs. Canvas makes a bitmap image, not a vector like an SVG. So, a higher resolution image requires a larger image file size.
