### ISSUE TITLE
Request for tab numbering

### ISSUE THREAD

**Issue by adigitoleo** [DaAwesomeP/tab-counter#16]
Hi, does anyone know of an extension to give tabs a number tag, like [this one](https://chrome.google.com/webstore/detail/tab-number/fijaenjgknobfdombbdchngpamggajpm?hl=en) but for Opera (running v52.0)? Is this a planned feature for this extension?

I would really like this as a workflow improvement since I use the ctrl+(No.) hotkey to switch between tabs, but when there are many tabs and it is past 10pm then my mental arithmetic is too slow :)

**Comment by DaAwesomeP** [comment]
Hi @adigitoleo,
I like the idea of this feature, but I would not be willing to implement it. There is a lot of performance trickery involved in modifying the title of every tab and updating the title whenever a tab is inserted, removed or rearranged. I am able to update the counter icon of every tab by only updating what is seen on screen first—this same trick cannot be done with the titles.

**Comment by adigitoleo** [comment]
I understand, in fact I have just switched to Vivaldi as my main browser since I was informed that they now have bookmark sync. Honestly opera is a bit lacking on the extensions side of things.

Anyway, good luck with your projects.

**Comment by Smile4ever** [comment]
@adigitoleo You can use https://addons.mozilla.org/en-US/firefox/addon/tab-numbering/ (https://github.com/tuomassalo/tab-numbering) together with Alt+1 .. Alt+9 or install one of these:
* https://addons.mozilla.org/en-US/firefox/addon/control-number-tab-switcher/
* https://addons.mozilla.org/en-US/firefox/addon/ctrl-number-to-switch-tabs/
