### ISSUE TITLE
Tab Counter button disappears from Menubar

### ISSUE THREAD

**Issue by nollinvoyd** [DaAwesomeP/tab-counter#17]
Fx 61.01, Win 10 Pro

If I place the button on the menubar, it disappears the next time I restart the browser.  I must reinstall the addon to meke it reappear.

If I place it on the nav bar, no problems.

thanks

**Comment by DaAwesomeP** [comment]
Hi,
I apologize for the delay in dealing with this issue. Are you still experiencing this issue? Please let me know what version of Tab Counter and Firefox you are using!

**Comment by DaAwesomeP** [comment]
Closing, as unconfirmed and inactive.
