### ISSUE TITLE
BUG: cannot dispaly current tab number in Firefox 60.2.1esr (32 bit)

### ISSUE THREAD

**Issue by ghsgz** [DaAwesomeP/tab-counter#18]
addons setting:
![default](https://user-images.githubusercontent.com/34056529/46239418-0be2f200-c3cb-11e8-91a1-9ad9e532fdc2.png)

my OS is win8.1, and its current look in my firefox like this:
![default](https://user-images.githubusercontent.com/34056529/46239441-519fba80-c3cb-11e8-9948-309ef4b78457.png)
![default](https://user-images.githubusercontent.com/34056529/46239449-6aa86b80-c3cb-11e8-88c7-dde8e63b3e87.png)

**Comment by ghsgz** [comment]
> add

Tab Counter version: 0.3.0

**Comment by DaAwesomeP** [comment]
Hi @ghzgz,
Thank you for providing complete screenshots and information about your environment.

What is your expected output here? The addon does not check for the current index of the selected tab in a window, it counts the sum of the total number of tabs in a window or all of the windows. However, the functionality I think you're talking about is something I would welcome in a pull request.

Please let me know if I misunderstand the issue!

**Comment by DaAwesomeP** [comment]
Great! I'll close this issue. Thank you for reporting--better safe than sorry!

No, it should be 14. It is not saying that the 13th tab is selected. It is saying that there are 14 tabs in the current window. If you open a second window with its own set of tabs, then that total will be added to the "All Windows" sum.
