### ISSUE TITLE
number of windows

### ISSUE THREAD

**Issue by HuBandiT** [DaAwesomeP/tab-counter#19]
Greetings,

I would like to have the number of windows displayed as well. (If not too difficult to develop and doesn't hurt performance much.)

aTdHvAaNnKcSe

**Comment by DaAwesomeP** [comment]
Hi @HuBandiT,
This shouldn't be too difficult to add! I'll mark it for the next version.

**Comment by HuBandiT** [comment]
Thank you in advance!

**Comment by DaAwesomeP** [comment]
@HuBandiT, I have released v0.4.0 on GitHub and AMO! You will find the new option to count the total number of windows in this version.

https://github.com/DaAwesomeP/tab-counter/releases/tag/v0.4.0
https://addons.mozilla.org/en-US/firefox/addon/tab-counter-webext/versions/?page=1#version-0.4.0

**Comment by HuBandiT** [comment]
( Yikes how many windows I have! )

Confirmed! Thank you!
