### ISSUE TITLE
Vivaldi

### ISSUE THREAD

**Issue by kevinmcfarlane** [DaAwesomeP/tab-counter#20]
Will the Opera version work in Vivaldi? If not is it easy to create a version that will? I currently use another one in Vivaldi but I like yours.

**Comment by DaAwesomeP** [comment]
Hi,
I do not know if the addon supports Vivaldi, but if it is WebExtension compatible, the it shouldn't be hard to try. I do not officially support Vivaldi.

Please go to the [lastest release](https://github.com/DaAwesomeP/tab-counter/releases/latest) and download the Opera version. You can try installing that ZIP archive or unzipping it and installing the unpacked extension in Vivaldi (this is how most Chrome-based browsers work).

Let me know if there is any other way that I can help you!
