### ISSUE TITLE
Dark outline makes it difficult to discern in dark themes

### ISSUE THREAD

**Issue by cubetastic33** [DaAwesomeP/tab-counter#27]
As the outline of the icon is black, it's difficult/impossible to see it in dark backgrounds. Could you change it to a color that's visible in both light and dark backgrounds? Here's a screenshot:
![image](https://user-images.githubusercontent.com/33519300/70326783-6099bc80-185b-11ea-9e31-a94b4643567b.png)

**Comment by cubetastic33** [comment]
I just figured out how to fix this; there's an option in preferences. Sorry!

**Comment by DaAwesomeP** [comment]
No problem! I'm sorry that I didn't get back to you faster!

**Comment by cubetastic33** [comment]
Shouldn't it choose the light outline by default if I was using a dark theme, though?

**Comment by DaAwesomeP** [comment]
Hmmm, yes it should. I believe I put this in the Firefox manifest. Unfortunately, I do not remember anymore how the detection works exactly. I welcome you to investigate it more if you are interested.
