### ISSUE TITLE
Counter is 1 px off screen when counter reaches over 1000

### ISSUE THREAD

**Issue by Sharingisnotillegal** [DaAwesomeP/tab-counter#43]
Having 1112 tabs currently in firefox, and the 2 is 1, maybe 2 pixels cut off on the right side, while the left side of the grey box is still not to its edges.

Also, not the right place to put this but.. Your homepages "contact me" form doesnt allow 7 as answer, only the number in english

**Comment by DaAwesomeP** [comment]
Hi @Sharingisnotillegal,

Unfortunately the extension has no control over the sizing spacing, or font of the badge; that is controlled by the browser so there is not much that can be done.

Hah thank you for letting me know...though I cannot replicate the issue. Typing "7" unlocks the form immediately for me... I will investigate that more.
