### ISSUE TITLE
Merge with the drop down arrow？

### ISSUE THREAD

**Issue by ivysrono** [DaAwesomeP/tab-counter#5]
Now：
![default](https://user-images.githubusercontent.com/2649544/28245272-823b6d74-6a35-11e7-8550-3de655885872.png)

https://userstyles.org/styles/79050/firefox-tabs-counter
![default](https://user-images.githubusercontent.com/2649544/28245299-1c3980a0-6a36-11e7-95b3-63371b5a9cbf.png)

Install them both
![default](https://user-images.githubusercontent.com/2649544/28245310-3c4d5858-6a36-11e7-9aa7-3de6ba2e320e.png)

**Comment by DaAwesomeP** [comment]
I'm not sure that I can do that. My addon is a WebExtension, so I'm limited with what I can do with the icon. The badge that I'm using to show the counter is a rigid API. I have no control ovwr CSS in the toolbar. I did this to ensure that my tab counter will work in Firefox v57+ when old addons using the older API will be disabled.

**Comment by DaAwesomeP** [comment]
Closing until there is a workaround or new API function.
