### ISSUE TITLE
If a count is already known and a new tab is opened, do not display "wait" for 1 second

### ISSUE THREAD

**Issue by Smile4ever** [DaAwesomeP/tab-counter#6]
Displaying "wait" instead of the current count (or current count + 1) doesn't make a lot of sense when I just opened a new tab.

Or is there a specific reason for this?

Kind regards,
Geoffrey

**Comment by DaAwesomeP** [comment]
Please see issue #1. When the browser starts, a window is restored, or many new tabs are created, this method stops the counter from negatively impacting browser performance. Running an event as soon as the tabs open is too much.

**Comment by DaAwesomeP** [comment]
If you come up with a better way to handle the events, I would love to implement it!

**Comment by Smile4ever** [comment]
I've looked at bug #1 and I understand.

Could you prevent to display "wait" when a previous count is already known, and just do +1 (since you can display "wait", I assume you know a tab is being added)? That would solve this issue. In the worst case it would display the count wrong for one second. I assume the performance of setting "wait" versus "count + 1" is the same.

**Comment by Smile4ever** [comment]
If you want to be sure you're on an about:newtab or about:blank page, you can check using the tabs API :)

**Comment by DaAwesomeP** [comment]
> Could you prevent to display "wait" when a previous count is already known, and just do +1 (since you can display "wait", I assume you know a tab is being added)? That would solve this issue. In the worst case it would display the count wrong for one second. I assume the performance of setting "wait" versus "count + 1" is the same.

I would rather never show a wrong count. The average user would perceive that as a bug. The addon doesn't actually store the tab count itself, the addon always queries the API for it. Otherwise the addon would have to be sure to clear the counts and keep track of individual windows. The performance lag seems to come from the combo of the events firing so much, querying the tab API, and updating the badge.

> If you want to be sure you're on an about:newtab or about:blank page, you can check using the tabs API

I would just run a different function for the new tab event. Unfortunately, I would still need a way to handle an influx of tabs vs one new tab. Handling the event so many times causes lag even with a debounce on the function.

**Comment by dev-rke** [comment]
> I would still need a way to handle an influx of tabs vs one new tab. Handling the event so many times causes lag even with a debounce on the function.

Hm, what about this idea:
Currently the debounce triggers only after 250ms.
You could also render the update when the first event occurs. 
Also keep the debounce, but let it also render initially a single time.

Take a look into the debounce function (https://lodash.com/docs/4.17.4#debounce):
```
{
  leading: true,
  trailing: true,
}
```
Maybe this might solve the issue.

**Comment by DaAwesomeP** [comment]
@dev-rke that's a good idea. I could make a second debounce of like 2000ms that fires on the leading first event for only the tab activate event. I'm going to push v0.2.0 with the harmless tooltip feature. I'll slot this for v0.2.1.

**Comment by DaAwesomeP** [comment]
Please try out this new build. If you open one new tab, there is nearly no delay in updating the badge. If you open(and switch to/activate) more than one quickly, then it will apply the delay.

Basically, I added a second, non-delayed leading debounce of one second to the activate event:
```js
// Prioritize active leading edge of every 1 second on tab switch (fluid update for new tabs)
const lazyActivateUpdateIcon = _.debounce(updateIcon, 1000, { leading: true })

browser.tabs.onActivated.addListener(() => {
  // Run normal update for most events
  update()

  // Prioritize active (fluid update for new tabs)
  lazyActivateUpdateIcon()
})

```
[tab-counter.opera.zip](https://github.com/DaAwesomeP/tab-counter/files/1229960/tab-counter.opera.zip)
[tab-counter.firefox.zip](https://github.com/DaAwesomeP/tab-counter/files/1229961/tab-counter.firefox.zip)

**Comment by Smile4ever** [comment]
It's better than it was, so it's an improvement. Thank you. Let's release 0.2.1!
