### ISSUE TITLE
Add a useful tooltip to the toolbar icon

### ISSUE THREAD

**Issue by Smile4ever** [DaAwesomeP/tab-counter#7]
A useful tooltip would contain this information:
Tab Counter (version maybe?)
5 tabs in current window
184 tabs in all windows

It's useful because when you have too many tabs open, it can no longer display the correct number. A tooltip would help in these cases.

**Comment by DaAwesomeP** [comment]
There already is a tool tip. Try clicking the badge.

**Comment by Smile4ever** [comment]
I see, it's a popup, not a tooltip. Would you consider a tooltip as well? That saves me a click :)

You do it like this:
browser.browserAction.setTitle({title: "Tab Counter\n15 tabs in this window\n50 tabs in all windows"});

**Comment by DaAwesomeP** [comment]
I did not realize that the title acted as a tool tip! I will push that this week.

**Comment by DaAwesomeP** [comment]
Pushed 9f62ad9828b5129496708069ceee1c141b032df1

**Comment by DaAwesomeP** [comment]
v0.2.0 has been released
https://github.com/DaAwesomeP/tab-counter/releases/tag/v0.2.0
https://addons.mozilla.org/en-US/firefox/addon/tab-counter-webext/versions/?page=1#version-0.2.0
